# CMake generated Testfile for 
# Source directory: C:/Users/user/Documents/app/music_elf
# Build directory: C:/Users/user/Documents/app/music_elf/build_ninja
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pitch_detector_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/pitch_detector_tests.exe")
set_tests_properties([=[pitch_detector_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;67;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[note_segmenter_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/note_segmenter_tests.exe")
set_tests_properties([=[note_segmenter_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;68;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[rhythm_dynamics_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/rhythm_dynamics_tests.exe")
set_tests_properties([=[rhythm_dynamics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;69;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[harmony_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/harmony_tests.exe")
set_tests_properties([=[harmony_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;70;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[arrangement_midi_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/arrangement_midi_tests.exe")
set_tests_properties([=[arrangement_midi_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;71;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[audio_renderer_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/audio_renderer_tests.exe")
set_tests_properties([=[audio_renderer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;72;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[lyrics_musicxml_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/lyrics_musicxml_tests.exe")
set_tests_properties([=[lyrics_musicxml_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;73;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[audio_io_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/audio_io_tests.exe")
set_tests_properties([=[audio_io_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;74;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[pipeline_integration_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/pipeline_integration_tests.exe")
set_tests_properties([=[pipeline_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;75;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[c_api_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/c_api_tests.exe")
set_tests_properties([=[c_api_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;76;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[model_interfaces_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/model_interfaces_tests.exe")
set_tests_properties([=[model_interfaces_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;77;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[midi_catalog_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/midi_catalog_tests.exe")
set_tests_properties([=[midi_catalog_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;78;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[export_snapshot_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/export_snapshot_tests.exe")
set_tests_properties([=[export_snapshot_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;79;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[cli_end_to_end_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/cli_end_to_end_tests.exe" "C:/Users/user/Documents/app/music_elf/build_ninja/music_elf_cli.exe")
set_tests_properties([=[cli_end_to_end_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;89;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[music_elf_cli_help]=] "C:/Users/user/Documents/app/music_elf/build_ninja/music_elf_cli.exe" "--help")
set_tests_properties([=[music_elf_cli_help]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;91;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[acapella_real_audio_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/acapella_real_audio_tests.exe")
set_tests_properties([=[acapella_real_audio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;59;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;93;add_music_elf_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
add_test([=[acapella_cli_tests]=] "C:/Users/user/Documents/app/music_elf/build_ninja/acapella_cli_tests.exe" "C:/Users/user/Documents/app/music_elf/build_ninja/music_elf_cli.exe")
set_tests_properties([=[acapella_cli_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Documents/app/music_elf/CMakeLists.txt;109;add_test;C:/Users/user/Documents/app/music_elf/CMakeLists.txt;0;")
